[2021-11-20 14:49:26,304][MainThread:16520][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-20 14:49:26,681][MainThread:16520][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-20 14:53:39,678][MainThread:21148][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-20 14:53:46,518][MainThread:21148][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:34:23,527][MainThread:27532][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:34:55,446][MainThread:27532][task_id:root][logs_util.py:82][ERROR][测试用例id=2,标题:获取设备信息,执行报错信息:Expecting property name enclosed in double quotes: line 1 column 37 (char 36)]
[2021-11-22 10:35:22,401][MainThread:27532][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:37:24,253][MainThread:22004][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:37:24,256][MainThread:22004][task_id:root][logs_util.py:82][ERROR][测试用例id=2,标题:获取设备信息,执行报错信息:Expecting property name enclosed in double quotes: line 1 column 37 (char 36)]
[2021-11-22 10:38:05,413][MainThread:22004][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:39:16,081][MainThread:23980][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:46:35,945][MainThread:28940][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:46:35,947][MainThread:28940][task_id:root][logs_util.py:82][ERROR][测试用例id=2,标题:获取设备信息,执行报错信息:Expecting property name enclosed in double quotes: line 1 column 37 (char 36)]
[2021-11-22 10:46:43,668][MainThread:28940][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:46:47,725][MainThread:28940][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:47:44,584][MainThread:29216][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:49:35,681][MainThread:10600][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:51:56,574][MainThread:29452][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:52:51,328][MainThread:29452][task_id:root][logs_util.py:82][ERROR][测试用例id=2,标题:获取设备信息,执行报错信息:list indices must be integers or slices, not str]
[2021-11-22 10:52:53,166][MainThread:29452][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:52:56,382][MainThread:29452][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 10:56:17,174][MainThread:15376][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 10:59:15,862][MainThread:22036][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 11:00:23,893][MainThread:14068][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 11:00:23,897][MainThread:14068][task_id:root][logs_util.py:82][ERROR][测试用例id=2,标题:获取设备信息,执行报错信息:list indices must be integers or slices, not str]
[2021-11-22 11:07:35,103][MainThread:29472][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 11:12:41,570][MainThread:13224][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 11:29:01,207][MainThread:28956][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 13:18:43,598][MainThread:892][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 14:03:08,361][MainThread:28512][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 14:40:25,054][MainThread:28752][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 14:40:25,061][MainThread:28752][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 14:40:25,802][MainThread:28752][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 14:40:25,808][MainThread:28752][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 14:40:26,600][MainThread:28752][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 14:40:26,611][MainThread:28752][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 14:43:08,932][MainThread:6260][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 14:43:08,937][MainThread:6260][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 14:43:09,664][MainThread:6260][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 14:43:09,671][MainThread:6260][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 14:43:10,461][MainThread:6260][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 14:43:10,473][MainThread:6260][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 14:43:11,040][MainThread:6260][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 14:43:11,493][MainThread:6260][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 15:00:52,827][MainThread:27800][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 15:01:03,790][MainThread:27800][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:01:04,548][MainThread:27800][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 15:01:28,604][MainThread:27800][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:01:29,404][MainThread:27800][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 15:01:36,124][MainThread:27800][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 15:02:20,780][MainThread:27800][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 15:03:16,062][MainThread:27800][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 15:04:17,010][MainThread:1356][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 15:04:26,568][MainThread:1356][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:04:27,365][MainThread:1356][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 15:04:56,480][MainThread:1356][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:04:57,214][MainThread:1356][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 15:05:09,253][MainThread:1356][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 15:06:13,589][MainThread:1356][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 15:07:49,184][MainThread:1356][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 15:09:06,932][MainThread:26904][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 15:09:06,935][MainThread:26904][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:09:07,655][MainThread:26904][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 15:09:07,658][MainThread:26904][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:09:08,436][MainThread:26904][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 15:09:08,446][MainThread:26904][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 15:11:13,781][MainThread:26904][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 15:18:07,989][MainThread:22200][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 15:18:10,501][MainThread:22200][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:18:11,303][MainThread:22200][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 15:18:11,316][MainThread:22200][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 15:18:12,106][MainThread:22200][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 15:18:12,122][MainThread:22200][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 16:15:40,520][MainThread:21748][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 16:15:40,527][MainThread:21748][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 16:15:41,307][MainThread:21748][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 16:15:41,314][MainThread:21748][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 16:15:42,085][MainThread:21748][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 16:15:42,098][MainThread:21748][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 16:17:15,193][MainThread:26864][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=1,通过情况pass=True.]
[2021-11-22 16:17:15,198][MainThread:26864][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 16:17:15,980][MainThread:26864][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/user/account/login HTTP/1.1" 200 None]
[2021-11-22 16:17:15,986][MainThread:26864][task_id:urllib3.connectionpool][connectionpool.py:971][DEBUG][Starting new HTTPS connection (1): ergoeu.ergomotion.com:443]
[2021-11-22 16:17:16,715][MainThread:26864][task_id:urllib3.connectionpool][connectionpool.py:452][DEBUG][https://ergoeu.ergomotion.com:443 "POST /garmin/device/getBedInfo HTTP/1.1" 200 None]
[2021-11-22 16:17:16,725][MainThread:26864][task_id:root][logs_util.py:78][INFO][更新测试用例执行结果,受影响行数row=1,测试用例id=2,通过情况pass=True.]
[2021-11-22 16:17:17,739][MainThread:26864][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2021-11-22 16:21:49,608][MainThread:10436][task_id:root][logs_util.py:78][INFO][Mail 发送成功]
[2022-01-27 14:18:16,018][MainThread:8640][task_id:root][logs_util.py:82][ERROR][(1136, "Column count doesn't match value count at row 1")]
[2022-01-27 14:18:32,867][MainThread:8640][task_id:root][logs_util.py:82][ERROR][(1136, "Column count doesn't match value count at row 1")]
[2022-01-27 14:19:40,745][MainThread:11348][task_id:root][logs_util.py:82][ERROR][(1136, "Column count doesn't match value count at row 1")]
[2022-01-27 14:19:40,746][MainThread:11348][task_id:root][logs_util.py:82][ERROR][(1136, "Column count doesn't match value count at row 1")]
[2022-01-27 14:24:03,737][MainThread:12484][task_id:root][logs_util.py:82][ERROR][(1062, "Duplicate entry '1' for key 'case.PRIMARY'")]
[2022-01-27 14:24:03,739][MainThread:12484][task_id:root][logs_util.py:82][ERROR][(1062, "Duplicate entry '2' for key 'case.PRIMARY'")]
